### ISSUE TITLE
Plugin thinks it's incompatible with latest IDEA (EAP)

### ISSUE THREAD

**Issue by chadselph** [shyim/idea-1password#13]
<img width="315" alt="Screenshot 2023-10-05 at 15 30 37" src="https://github.com/shyim/idea-1password/assets/315988/15140a27-be4b-4130-9bf6-34f6c459441e">

I think this version just needs to be bumped; I haven't tested it locally but I can't imagine any breaking changes for what this plugin does. If you're too busy I can verify everything works on EAP.

https://github.com/shyim/idea-1password/blob/main/gradle.properties#L7

**Comment by shyim** [comment]
I tagged a new release. It should be rolled out in few hours after review

**Comment by shyim** [comment]
https://plugins.jetbrains.com/plugin/19698-1password/versions/stable/411851
