### ISSUE TITLE
IDEA 2024 is in RC mode

### ISSUE THREAD

**Issue by chadselph** [shyim/idea-1password#15]
I think we should mark it compatible with the latest IDEA 2024, currently we get this error

![Screenshot 2024-03-31 at 22 06 13](https://github.com/shyim/idea-1password/assets/315988/e27210ae-61ac-4ba2-8ebc-c3521e76ff63)

**Comment by shyim** [comment]
Is in review at Jetbrains. should be approved soon https://plugins.jetbrains.com/plugin/19698-1password/versions/stable/514883
