### ISSUE TITLE
Ability to provide secret as argument value in run configuration

### ISSUE THREAD

**Issue by bric3** [shyim/idea-1password#2]
Similarly to #1 it might also be useful in some case to be able to have argument provider whose value is a secret that can be fetched in 1Password.

<img width="681" alt="image" src="https://user-images.githubusercontent.com/803621/206416235-fcdde401-121c-4ac6-bc92-830a71bf61d7.png">

```
op item get "finnhub" --fields "token"
```

That said I understand that the IntelliJ SDK must provide a facility for such a feature.

**Comment by shyim** [comment]
That should work now with https://github.com/shyim/idea-1password/pull/11
